In [1]:
# Title: DMRG for Bachelor Thesis
# Author: Aaron Sander
# Date: March 2020

# This program is used for initial learning of tensor network methods
# to be used in my bachelor thesis.
# It is an implementation of Matrix Product States (MPS) and Density Matrix
# Renormalization Group (DMRG) for finding the ground state of an arbitrary
# Hamiltonian

In [2]:
######################### IMPORTS #############################################
import numpy as np

In [3]:
######################## CLASSES ##############################################
class matrixProductOperator:
    def __init__(self, left_bound, inner, right_bound):
        # Leftmost lattice position
        self.left_bound = left_bound
        # Middle lattice positions
        self.inner = inner
        # Rightmost lattice position
        self.right_bound = right_bound


class matrixProductState:
    def __init__(self, left_bound, inner, right_bound):
        self.left_bound = left_bound
        self.inner = inner
        self.right_bound = right_bound

In [4]:
###################### FUNCTIONS ##############################################
# Used to contract tensors horizontally from A->B
# All 2 dimensional tensors have dimensions (ij) or (ab)
# All 3 dimensional tensors have dimensions (ijk) or (abc)
# All 4 dimensional tensors have dimensions (ijkl) or (abcd)

# Examples:
# 4-tensor: Inner MPO
# 3-tensor: Inner MPS, Outer MPO, Half contracted inner MPO-MPS
# 2-tensor: Outer MPS, Half contracted outer MPO-MPS, Fully contracted lattice point

# This all works assuming the MPS has form (2 x d), (d x d x 2), (2 x d)

# How to read: If we are at tensor A, what other tensor B can I contract with?
def contract_horizontal(A, B, dir):
    if A.ndim == 3:
        if B.ndim == 4: 
            if dir =='right':
                tensor = np.einsum('ijk, ibcd->bjckd', A, B)
                # Reshape to (b, j*c, k*d)
                tensor = np.reshape(tensor, (B.shape[1], A.shape[1]*B.shape[2], A.shape[2]*B.shape[3]))
            elif dir == 'left':
                tensor = np.einsum('ijk, aicd->ajckd', A, B)
                # Reshape to (a, j*c, k*d)
                tensor = np.reshape(tensor, (B.shape[0], A.shape[1]*B.shape[2], A.shape[2]*B.shape[3]))
        elif B.ndim == 3: # Used for contraction of MPO itself
            if dir == 'right' or 'left':  # Can be removed, left for readability
                tensor = np.einsum('ijk, ibc->jbkc', A, B)
                # Reshape collapses indices to (j*b, k*c)
                tensor = np.reshape(tensor, (A.shape[1]*B.shape[1], A.shape[2]*B.shape[2]))
    
    elif A.ndim == 2:
        if B.ndim == 3:
            if dir == 'right':
                tensor = np.einsum('ij, jbc->icb', A, B)
                # Reshape to (i*c, b)
                tensor = np.reshape(tensor, (A.shape[0]*B.shape[2], B.shape[1]))
            elif dir == 'left':
                tensor = np.einsum('ij, ajc->ica', A, B)
                # Reshape to (i*c, a)
                tensor = np.reshape(tensor, (A.shape[0]*B.shape[2], B.shape[0]))
        elif B.ndim == 2:
            if dir == 'right' or 'left': # Direction independent since both MPS edges are (2 x d)
                tensor = np.einsum('ij, aj->ia', A, B)
                # Reshape to (i*b)
                tensor = np.reshape(tensor, (A.shape[0]*B.shape[0]))

    elif A.ndim == 1:
        if B.ndim == 2: # Final contraction before scalar product
            if dir == 'right':
                tensor = np.einsum('i, ib->b', A, B)
            elif dir == 'left':
                tensor = np.einsum('i, ai->a', A, B)
        elif B.ndim == 1: # Inner product
            tensor = np.einsum('i, i', A, B)

    return tensor


def contract_vertical(A, B, dir):
    if A.ndim == 3:
        if B.ndim == 4:
            if dir == 'down' or 'up':
                tensor = np.einsum('ijk, abkd->iajbd', A, B) # Contracts (d x d x 2) and (3 x 3 x 2 x 2)
                # Reshape to (i*a, j*b, d)
                tensor = np.reshape(tensor, (A.shape[0]*B.shape[0], A.shape[1]*B.shape[1], B.shape[3]))
        elif B.ndim == 3:
            if dir == 'down' or 'up': # Contract (3d x 3d x 2) and (d x d x 2)
                tensor = np.einsum('ijk, abk->iajb', A, B)
                # Reshape to (i*a, j*b)
                tensor = np.reshape(tensor, (A.shape[0]*B.shape[0], A.shape[1]*B.shape[1]))

    elif A.ndim == 2:
        if B.ndim == 3:
            if dir == 'down':  # From Bra->Operator->Ket
                tensor = np.einsum('ij, abi->jab', A, B) # Contract (2 x d) and (3 x 2 x 2)
                # Reshape to (j*a, b)
                tensor = np.reshape(tensor, (A.shape[1]*B.shape[0], B.shape[1]))
            elif dir == 'up':  # From Ket->Operator->Bra
                tensor = np.einsum('ij, aic->jac', A, B)
                # Reshape to (j*a, c)
                tensor = np.reshape(tensor, (A.shape[1]*B.shape[0], B.shape[2]))
        elif B.ndim == 2:
            if dir == 'down' or 'up':
                tensor = np.einsum('ij, jb->ib', A, B) # Contract (3d x 2) and (2 x d)
                # Reshape to (i*b)
                tensor = np.reshape(tensor, (A.shape[0]*B.shape[1]))

    return tensor


def calculateExpectation(MPS_bra, MPO, MPS_ket, vert_dir, horiz_dir):
    # Initialize list of tensors
    tensor = [None]*N

    # Contract <MPS|MPO|MPS> at each lattice position
    # Down: Bra -> MPO -> Ket
    # Up: Ket -> MPO -> Bra
    for i in range(0, N):
        if vert_dir == 'down':
            first_contraction = contract_vertical(MPS_bra[i], MPO[i], vert_dir)
            tensor[i] = contract_vertical(first_contraction, MPS_ket[i], vert_dir)
        if vert_dir == 'up':
            first_contraction = contract_vertical(MPS_ket[i], MPO[i], vert_dir)
            tensor[i] = contract_vertical(first_contraction, MPS_bra[i], vert_dir)

    # Contract each tensor created from above
    # Left and right necessary for scanning in DMRG
    if horiz_dir == 'right':
        E = tensor[0]
        for i in range(1, len(tensor)):
            E = contract_horizontal(E, tensor[i], horiz_dir)
    if horiz_dir == 'left':
        E = tensor[-1]
        for i in range(len(tensor)-2, -1, -1):
            E = contract_horizontal(E, tensor[i], horiz_dir)

    return E

# TODO: Determine if vertical/horizontal can be generalized and combined
# TODO: Use tensordot for better readability?
# NOTE: All directions of contractions have been tested and work correctly.
#       This was verified by checking if result is equal for going
#       left<->right and up<->down.

In [5]:
##################### INITIALIZATION MPO ######################################
# Operators
pauli_z = np.array([[1, 0],
                    [0, -1]])

pauli_x = np.array([[0, 1],
                    [1, 0]])

zero = np.zeros((2, 2))
identity = np.identity(2)
# Interaction parameter
g = 2
# Particles (Total lattice positions)
N = 3

# Initialization of Hamiltonian MPO (entries done by hand)
# Dimensions (1x3x2x2)->(3x2x2)
left_bound = np.array([identity, pauli_z, g*pauli_x])

# Dimensions (3x3x2x2)
inner = np.array([np.array([identity, pauli_z, g*pauli_x]),
                  np.array([zero, zero, pauli_z]),
                  np.array([zero, zero, np.identity(2)])])

# Dimensions (3x1x2x2)->3x2x2
right_bound = np.array([[g*pauli_x],
                        [pauli_z],
                        [identity]])
right_bound = np.squeeze(right_bound)  # Removes unnecessary index

MPO_initial = matrixProductOperator(left_bound, inner, right_bound)
MPO = [MPO_initial.left_bound] + [MPO_initial.inner]*(N-2) + [MPO_initial.right_bound]
# NOTE: The MPO never gets modified, so for a possible performance boost
#       we could just use the MPO_initial. For readability by indexing over
#       each position, we will expand it anyway so that it matches the MPS.

In [6]:
######################### INITIALIZATION MPS ##################################
# Bond Dimension
d = 5

state =  np.zeros((1, 2*d*d))
state[0, 0] = 1

# Dimensions (2 x d)
A_1 = np.random.rand(2, d)
#A_1 = np.zeros((2, d))
#A_1[0, 0] = 1

# Dimensions (d x d x 2)
A_i = np.random.rand(d, d, 2)
#A_i = np.reshape(state, (d, d, 2))

# Dimensions (2 x d)
A_N = np.random.rand(2, d)
#A_N = A_1

MPS_initial = matrixProductState(A_1, A_i, A_N)
MPS = [MPS_initial.left_bound] + [MPS_initial.inner]*(N-2) + [MPS_initial.right_bound]

In [7]:
######################### CANONICAL FORM #############################################
# Steps:
# 1. Reshape tensor to a matrix
# 2. Perform SVD such that A_k = USV
# 3. Update A_k --> A'_k = U
# 3. A_(k+1) must be reshaped to match dimensions of SV
# 4. Update A_(k+1) --> A'_(k+1) = SVA_(k+1)
# 5. Repeat for each site
# 6. Final site does not need to be decomposed

# # SVD
# U_1, S, VH_1 = np.linalg.svd(A_1)
# # Function only returns singular values, so we need it in matrix form
# S_1 = np.zeros((A_1.shape[0], A_1.shape[1]))
# S_1[:A_1.shape[0], :A_1.shape[0]] = np.diag(S)

# # Update A_K
# A_1_prime = U_1

# # Reshape A_(k+1) to dimensions of SV
# SV = S_1 @ VH_1
# A_i_prime = SV @ np.reshape(A_i, (SV.shape[1], d, 2))

In [8]:
# # Reshape
# temp = np.reshape(A_i_prime, (2, d))
# # SVD
# U_i, S, VH_i = np.linalg.svd(temp)
# # Function only returns singular values, so we need it in matrix form
# S_i = np.zeros((temp.shape[0], temp.shape[1]))
# S_i[:temp.shape[0], :temp.shape[0]] = np.diag(S)

# # Update A_K
# A_i_prime = U_i

# SV = S_i @ VH_i
# A_N_prime = SV @ np.reshape(A_N, (SV.shape[1], 2))

In [9]:
# 1. Decompose A_1
U_1, S, V_1 = np.linalg.svd(A_1)
S_1 = np.zeros((A_1.shape[0], A_1.shape[1]))
S_1[:A_1.shape[0], :A_1.shape[0]] = np.diag(S)

# 2. Set A_1_prime = U_1
A_1_prime = U_1

# 3. Update A_i_prime = SVA_i
SV = S_1 @ V_1
A_i_prime = contract_horizontal(SV, A_i, 'right')


#A_i_prime = np.reshape(A_i_prime, (SV.shape[0], d, 2))
# (First bond dimension x Given bond dimension x Physical dimension)

# 4. Decompose A_i_prime
temp = np.reshape(A_i_prime, (2*2, d))
U, S_vector, V = np.linalg.svd(temp)
S = np.zeros((temp.shape[0], temp.shape[1]))
S[:temp.shape[0], :temp.shape[0]] = np.diag(S_vector)

# 5. Set A_i_prime to U
A_i_prime = np.reshape(U, (int(U.shape[0]/2), int(U.shape[0]/2), U.shape[1]))

# 6. Update A_i+1 or A_N to A_N = SVA_N
SV = S @ V
A_N_prime = contract_horizontal(SV, A_N, 'right')
A_N_prime = np.reshape(A_N_prime, (int(A_N_prime.shape[0]/2), 2))

# 7. Switch directions and decompose A_N_prime
temp = A_N_prime
U, S_vector, V = np.linalg.svd(temp)
S = np.zeros((temp.shape[0], temp.shape[1]))
S[:temp.shape[1], :temp.shape[1]] = np.diag(S_vector)
#### Switch to 1, 1 for going to the left?

# 8. Set A_N_prime_prime = V
A_N_prime_prime = V # No need to reshape

# 9. Update A_i-1 or A_i with A_i = A_iUS
US = U @ S
A_i_prime_prime = np.einsum('ij, abi->abj', US, A_i_prime)

# NOTE: @ operator for multiplication contracts with the wrong index
#       Ex. (2x5) @ (5x5x2) = (5 x 2 x 2)?

# TODO: Set threshold for elements. If below X, set to 0.

In [10]:
MPS_prime = [A_1_prime] + [A_i_prime_prime] + [A_N_prime_prime]

In [11]:
E_D_R = calculateExpectation(MPS, MPO, MPS, 'down', 'right')
E_D_R_prime = calculateExpectation(MPS_prime, MPO, MPS_prime, 'down', 'right')

In [12]:
E_D_R

436.60950327574614

In [13]:
E_D_R_prime

240.34673186468177

In [27]:
np.matrix(MPS_prime[0]).H @ MPS_prime[0]

matrix([[1.00000000e+00, 1.11022302e-16],
        [1.11022302e-16, 1.00000000e+00]])

In [28]:
MPS_prime[0] @np.matrix(MPS_prime[0]).H

matrix([[1.00000000e+00, 2.22044605e-16],
        [2.22044605e-16, 1.00000000e+00]])

In [29]:
np.matrix(MPS_prime[2]).H @ MPS_prime[2]

matrix([[1., 0.],
        [0., 1.]])

In [30]:
MPS_prime[2] @np.matrix(MPS_prime[2]).H

matrix([[1., 0.],
        [0., 1.]])

In [33]:
np.matrix(np.reshape(MPS_prime[1], (2*2, 2))).H @ np.reshape(MPS_prime[1], (2*2, 2))

matrix([[ 7.53327425e+01, -1.66533454e-16],
        [-1.66533454e-16,  3.75914389e-02]])

In [31]:
# ######## EXPECTATION VALUE DOWN, RIGHT ##########
# Left lattice bra->H->ket
temp = contract_vertical(MPS_prime[0], MPO[0], 'down')
left = contract_vertical(temp, MPS_prime[0], 'down')

# Inner lattice bra->H->ket
temp = contract_vertical(MPS_prime[1], MPO[1], 'down')
inner = contract_vertical(temp, MPS_prime[1], 'down')

# Right lattice bra->H->ket
temp = contract_vertical(MPS_prime[2], MPO[2], 'down')
right = contract_vertical(temp, MPS_prime[2], 'down')

# temp = contract_horizontal(left, inner, 'right')
# E_down_right = contract_horizontal(temp, right, 'right')

In [32]:
left

array([ 1.        ,  0.        , -0.12123629,  0.99262368,  1.98524735,
        0.24247257,  0.        ,  1.        ,  0.99262368,  0.12123629,
        0.24247257, -1.98524735])

In [33]:
inner

array([[ 5.90360303e+01,  5.22156870e+01,  5.90171207e+01,
         5.22366851e+01,  2.98819457e+00, -3.37160698e-01,
         5.22156870e+01,  4.62209211e+01,  5.22366851e+01,
         4.61976037e+01, -3.37160698e-01, -2.93595724e+00],
       [-1.59900017e+00,  4.67396449e-02, -1.61037098e+00,
         6.86678144e-02,  8.57823968e-01, -1.73115046e+00,
        -1.42612482e+00,  6.32308433e-02, -1.41349807e+00,
         3.88806446e-02,  8.40038297e-01, -1.53462072e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  5.90171207e+01,  5.22366851e+01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  5.22366851e+01,  4.61976037e+01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00, -1.61037098e+00,  6.86678144e-02,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00, -1.41349807e+00,  3.88806446e-02],
       [ 0.00000000e+00,  0.00000000e+00,  0.0000000

In [56]:
right

array([ 0.,  2.,  1.,  0.,  1.,  0.,  2.,  0.,  0., -1.,  0.,  1.])

In [32]:
# # ############## MANUAL TESTS FOR N = 3 #################################
# # ####### CONTRACT HAMILTONIAN LEFT AND RIGHT ########
# temp = contract_horizontal(MPO[0], MPO[1], 'right')
# H_right = contract_horizontal(temp, MPO[2], 'right')
# temp = contract_horizontal(MPO[2], MPO[1], 'left')
# H_left = contract_horizontal(temp, MPO[0], 'left')
# if (H_right.all() == H_left.all()):
#     print("Hamiltonian contracts correctly")

# # ######## EXPECTATION VALUE DOWN, RIGHT ##########
# # Left lattice bra->H->ket
# temp = contract_vertical(MPS[0], MPO[0], 'down')
# left = contract_vertical(temp, MPS[0], 'down')

# # Inner lattice bra->H->ket
# temp = contract_vertical(MPS[1], MPO[1], 'down')
# inner = contract_vertical(temp, MPS[1], 'down')

# # Right lattice bra->H->ket
# temp = contract_vertical(MPS[2], MPO[2], 'down')
# right = contract_vertical(temp, MPS[2], 'down')

# temp = contract_horizontal(left, inner, 'right')
# E_down_right = contract_horizontal(temp, right, 'right')

# ###### EXPECTATION VALUE UP, RIGHT ###########
# # Left lattice ket->H->bra
# temp = contract_vertical(MPS[0], MPO[0], 'up')
# left = contract_vertical(temp, MPS[0], 'up')

# # Inner lattice ket->H->bra
# temp = contract_vertical(MPS[1], MPO[1], 'up')
# inner = contract_vertical(temp, MPS[1], 'up')

# # Right lattice ket->H->bra
# temp = contract_vertical(MPS[2], MPO[2], 'up')
# right = contract_vertical(temp, MPS[2], 'up')

# temp = contract_horizontal(left, inner, 'right')
# E_up_right = contract_horizontal(temp, right, 'right')

# ###### EXPECTATION VALUE UP, LEFT ###########
# # Right lattice bra->H->ket
# temp = contract_vertical(MPS[2], MPO[2], 'up')
# right = contract_vertical(temp, MPS[2], 'up')

# # Inner lattice bra->H->ket
# temp = contract_vertical(MPS[1], MPO[1], 'up')
# inner = contract_vertical(temp, MPS[1], 'up')

# # Left lattice bra->H->ket
# temp = contract_vertical(MPS[0], MPO[0], 'up')
# left = contract_vertical(temp, MPS[0], 'up')

# temp = contract_horizontal(right, inner, 'left')
# E_up_left = contract_horizontal(temp, left, 'left')

# ###### EXPECTATION VALUE DOWN, LEFT ###########
# # Right lattice bra->H->ket
# temp = contract_vertical(MPS[2], MPO[2], 'down')
# right = contract_vertical(temp, MPS[2], 'down')

# # Inner lattice bra->H->ket
# temp = contract_vertical(MPS[1], MPO[1], 'down')
# inner = contract_vertical(temp, MPS[1], 'down')

# # Left lattice bra->H->ket
# temp = contract_vertical(MPS[0], MPO[0], 'down')
# left = contract_vertical(temp, MPS[0], 'down')

# temp = contract_horizontal(right, inner, 'left')
# E_down_left = contract_horizontal(temp, left, 'left')

# ######## EXPECTATION VALUE ZIG-ZAG ##########
# # Left lattice bra->H->ket
# temp = contract_vertical(MPS[0], MPO[0], 'down')
# left = contract_vertical(temp, MPS[0], 'down')

# # Inner lattice ket->H->bra
# temp = contract_vertical(MPS[1], MPO[1], 'up')
# inner = contract_vertical(temp, MPS[1], 'up')

# # Right lattice bra->H->ket
# temp = contract_vertical(MPS[2], MPO[2], 'down')
# right = contract_vertical(temp, MPS[2], 'down')

# temp = contract_horizontal(left, inner, 'right')
# E_zig_zag = contract_horizontal(temp, right, 'right')

# if (E_down_right.all() == E_down_left.all() == E_up_right.all() == E_up_left.all() == E_zig_zag.all()):
#      print("Expectation value contracts in all directions correctly")

# ######################## EXPECTATION VALUE #############################################
# E_D_R = calculateExpectation(MPS, MPO, MPS, 'down', 'right')
# E_D_L = calculateExpectation(MPS, MPO, MPS, 'down', 'left')
# E_U_R = calculateExpectation(MPS, MPO, MPS, 'up', 'right')
# E_U_L = calculateExpectation(MPS, MPO, MPS, 'up', 'left')

# # Rounding necessary since sometimes the values are slightly off
# # Most likely due to rounding errors in computation
# if (np.round(E_D_R, 5) == np.round(E_D_L, 5)
#                        == np.round(E_U_R, 5)
#                        == np.round(E_U_L, 5)):
#     print("Expectation value is the same in all directions")
# print(E_D_R, E_D_L, E_U_R, E_U_L)

Hamiltonian contracts correctly
Expectation value contracts in all directions correctly
Expectation value is the same in all directions
466.18273134171596 466.18273134171585 466.18273134171596 466.18273134171585
