In [99]:
# Title: DMRG for Bachelor Thesis
# Author: Aaron Sander
# Date: March 2020

# This program is used for initial learning of tensor network methods
# to be used in my bachelor thesis.
# It is an implementation of Matrix Product States (MPS) and Density Matrix
# Renormalization Group (DMRG) for finding the ground state of an arbitrary
# Hamiltonian

In [100]:
######################### IMPORTS #############################################
import numpy as np

In [101]:
######################## CLASSES ##############################################
class matrixProductOperator:
    def __init__(self, left_bound, inner, right_bound):
        # Leftmost lattice position
        self.left_bound = left_bound
        # Middle lattice positions
        self.inner = inner
        # Rightmost lattice position
        self.right_bound = right_bound


class matrixProductState:
    def __init__(self, left_bound, inner, right_bound):
        self.left_bound = left_bound
        self.inner = inner
        self.right_bound = right_bound

In [102]:
###################### FUNCTIONS ##############################################
# Used to contract tensors horizontally from A->B
# All 2 dimensional tensors have dimensions (ij) or (ab)
# All 3 dimensional tensors have dimensions (ijk) or (abc)
# All 4 dimensional tensors have dimensions (ijkl) or (abcd)

# Examples:
# 4-tensor: Inner MPO
# 3-tensor: Inner MPS, Outer MPO, Half contracted inner MPO-MPS
# 2-tensor: Outer MPS, Half contracted outer MPO-MPS, Fully contracted lattice point

# This all works assuming the MPS has form (2 x d), (d x d x 2), (2 x d)

# How to read: If we are at tensor A, what other tensor B can I contract with?
def contract_horizontal(A, B, dir):
    if A.ndim == 3:
        if B.ndim == 4: 
            if dir =='right':
                tensor = np.einsum('ijk, ibcd->bjckd', A, B)
                # Reshape to (b, j*c, k*d)
                tensor = np.reshape(tensor, (B.shape[1], A.shape[1]*B.shape[2], A.shape[2]*B.shape[3]))
            elif dir == 'left':
                tensor = np.einsum('ijk, aicd->ajckd', A, B)
                # Reshape to (a, j*c, k*d)
                tensor = np.reshape(tensor, (B.shape[0], A.shape[1]*B.shape[2], A.shape[2]*B.shape[3]))
        elif B.ndim == 3: # Used for contraction of MPO itself
            if dir == 'right' or 'left':  # Can be removed, left for readability
                tensor = np.einsum('ijk, ibc->jbkc', A, B)
                # Reshape collapses indices to (j*b, k*c)
                tensor = np.reshape(tensor, (A.shape[1]*B.shape[1], A.shape[2]*B.shape[2]))
    
    elif A.ndim == 2:
        if B.ndim == 3:
            if dir == 'right':
                tensor = np.einsum('ij, jbc->icb', A, B)
                # Reshape to (i*c, b)
                tensor = np.reshape(tensor, (A.shape[0]*B.shape[2], B.shape[1]))
            elif dir == 'left':
                tensor = np.einsum('ij, ajc->ica', A, B)
                # Reshape to (i*c, a)
                tensor = np.reshape(tensor, (A.shape[0]*B.shape[2], B.shape[0]))
        elif B.ndim == 2:
            if dir == 'right' or 'left': # Direction independent since both MPS edges are (2 x d)
                tensor = np.einsum('ij, aj->ia', A, B)
                # Reshape to (i*b)
                tensor = np.reshape(tensor, (A.shape[0]*B.shape[0]))

    elif A.ndim == 1:
        if B.ndim == 2: # Final contraction before scalar product
            if dir == 'right':
                tensor = np.einsum('i, ib->b', A, B)
            elif dir == 'left':
                tensor = np.einsum('i, ai->a', A, B)
        elif B.ndim == 1: # Inner product
            tensor = np.einsum('i, i', A, B)

    return tensor


def contract_vertical(A, B, dir):
    if A.ndim == 3:
        if B.ndim == 4:
            if dir == 'down' or 'up':
                tensor = np.einsum('ijk, abkd->iajbd', A, B) # Contracts (d x d x 2) and (3 x 3 x 2 x 2)
                # Reshape to (i*a, j*b, d)
                tensor = np.reshape(tensor, (A.shape[0]*B.shape[0], A.shape[1]*B.shape[1], B.shape[3]))
        elif B.ndim == 3:
            if dir == 'down' or 'up': # Contract (3d x 3d x 2) and (d x d x 2)
                tensor = np.einsum('ijk, abk->iajb', A, B)
                # Reshape to (i*a, j*b)
                tensor = np.reshape(tensor, (A.shape[0]*B.shape[0], A.shape[1]*B.shape[1]))

    elif A.ndim == 2:
        if B.ndim == 3:
            if dir == 'down':  # From Bra->Operator->Ket
                tensor = np.einsum('ij, abi->jab', A, B) # Contract (2 x d) and (3 x 2 x 2)
                # Reshape to (j*a, b)
                tensor = np.reshape(tensor, (A.shape[1]*B.shape[0], B.shape[1]))
            elif dir == 'up':  # From Ket->Operator->Bra
                tensor = np.einsum('ij, aic->jac', A, B)
                # Reshape to (j*a, c)
                tensor = np.reshape(tensor, (A.shape[1]*B.shape[0], B.shape[2]))
        elif B.ndim == 2:
            if dir == 'down' or 'up':
                tensor = np.einsum('ij, jb->ib', A, B) # Contract (3d x 2) and (2 x d)
                # Reshape to (i*b)
                tensor = np.reshape(tensor, (A.shape[0]*B.shape[1]))

    return tensor


def calculateExpectation(MPS_bra, MPO, MPS_ket, vert_dir, horiz_dir):
    # Initialize list of tensors
    tensor = [None]*N

    # Contract <MPS|MPO|MPS> at each lattice position
    # Down: Bra -> MPO -> Ket
    # Up: Ket -> MPO -> Bra
    for i in range(0, N):
        if vert_dir == 'down':
            first_contraction = contract_vertical(MPS_bra[i], MPO[i], vert_dir)
            tensor[i] = contract_vertical(first_contraction, MPS_ket[i], vert_dir)
        if vert_dir == 'up':
            first_contraction = contract_vertical(MPS_ket[i], MPO[i], vert_dir)
            tensor[i] = contract_vertical(first_contraction, MPS_bra[i], vert_dir)

    # Contract each tensor created from above
    # Left and right necessary for scanning in DMRG
    if horiz_dir == 'right':
        E = tensor[0]
        for i in range(1, len(tensor)):
            E = contract_horizontal(E, tensor[i], horiz_dir)
    if horiz_dir == 'left':
        E = tensor[-1]
        for i in range(len(tensor)-2, -1, -1):
            E = contract_horizontal(E, tensor[i], horiz_dir)

    return E

def left_canonical(MPS, N):
    for i in range(0, N):
        if i == 0:
            M = np.reshape(MPS[i], (MPS[i].shape[0], MPS[i].shape[1]))
            U, S_vector, V = np.linalg.svd(M, full_matrices=False)
            S = np.diag(S_vector)
            MPS[i] = U
            MPS[i+1] = np.einsum('ij, jbc->ibc', S @ V, MPS[i+1])
        elif i != N-1:
            # Reshape to Matrix such that first leg is bond dimension*physical dimension
            M = np.reshape(MPS[i], (MPS[i].shape[0]*MPS[i].shape[2], MPS[i].shape[1]))
            # Decompose
            U, S_vector, V = np.linalg.svd(M, full_matrices=False)
            S = np.diag(S_vector)

            # Set current position to U
            # Shape (last bond dimension, new bond dimension, physical dimension)
            # so that (Connects to previous tensor, connects to next tensor, connects to MPO)
            # Last bond dimension = U dimension - physical dimension
            MPS[i] = np.reshape(U, (MPS[i].shape[0], len(S_vector), MPS[i].shape[2]))
            # Update next position
            if i == N-2: # Second to last element
                MPS[i+1] = np.einsum('ij, jb->ib', S @ V, MPS[i+1].T).T # Transpose due to convention of using 2 x d for last position
            else:
                MPS[i+1] = np.einsum('ij, jbc->ibc', S @ V, MPS[i+1])
        elif i == N-1:
            M = np.reshape(MPS[i], (MPS[i].shape[0]*MPS[i].shape[1], 1))
            U, S_vector, V = np.linalg.svd(M, full_matrices=False)
            MPS[i] = np.reshape(U, (MPS[i].shape[0], MPS[i-1].shape[1])) # 2 x d convention
            print("Singular Value:", S_vector)
    return MPS

# TODO: Determine if vertical/horizontal can be generalized and combined
# TODO: Use tensordot for better readability?
# NOTE: All directions of contractions have been tested and work correctly.
#       This was verified by checking if result is equal for going
#       left<->right and up<->down.

In [103]:
##################### INITIALIZATION MPO ######################################
### Quantum Ising Model ###
# Operators
pauli_z = np.array([[1, 0],
                    [0, -1]])

pauli_x = np.array([[0, 1],
                    [1, 0]])

zero = np.zeros((2, 2))
identity = np.identity(2)
# Interaction parameter
g = 2
# Particles (Total lattice positions)
N = 15

# Initialization of Hamiltonian MPO (entries done by hand)
# Dimensions (1x3x2x2)->(3x2x2)
left_bound = np.array([identity, pauli_z, g*pauli_x])

# Dimensions (3x3x2x2)
inner = np.array([np.array([identity, pauli_z, g*pauli_x]),
                  np.array([zero, zero, pauli_z]),
                  np.array([zero, zero, np.identity(2)])])

# Dimensions (3x1x2x2)->3x2x2
right_bound = np.array([[g*pauli_x],
                        [pauli_z],
                        [identity]])
right_bound = np.squeeze(right_bound)  # Removes unnecessary index

MPO_initial = matrixProductOperator(left_bound, inner, right_bound)
MPO = [MPO_initial.left_bound] + [MPO_initial.inner]*(N-2) + [MPO_initial.right_bound]
# NOTE: The MPO never gets modified, so for a possible performance boost
#       we could just use the MPO_initial. For readability by indexing over
#       each position, we will expand it anyway so that it matches the MPS.

In [104]:
######################### INITIALIZATION MPS ##################################
### W State ###
d = 2

A_1 = np.array([[1, 0], [0, 1]])

A_i = np.array([np.array([[1, 0],
                          [0, 1]]),
                np.array([[0, 1],
                          [0, 0]])])

A_N = np.array([np.array([[1],
                          [0]]),
                np.array([[0],
                          [1]])])
A_N = np.squeeze(A_N)

## Random state ###
# Bond Dimension
# d = 2

# state =  np.zeros((1, 2*d*d))
# state[0, 0] = 1

# # Dimensions (2 x d)
# A_1 = np.random.rand(2, d)

# # Dimensions (d x d x 2)
# A_i = np.random.rand(d, d, 2)



# # Dimensions (2 x d)
# A_N = np.random.rand(2, d)

MPS_initial = matrixProductState(A_1, A_i, A_N)
MPS = [MPS_initial.left_bound] + [MPS_initial.inner]*(N-2) + [MPS_initial.right_bound]

In [105]:
######################## EXPECTATION VALUE #############################################
E_D_R = calculateExpectation(MPS, MPO, MPS, 'down', 'right')
E_D_L = calculateExpectation(MPS, MPO, MPS, 'down', 'left')
E_U_R = calculateExpectation(MPS, MPO, MPS, 'up', 'right')
E_U_L = calculateExpectation(MPS, MPO, MPS, 'up', 'left')

# Rounding necessary since sometimes the values are slightly off
# Most likely due to rounding errors in computation
if (np.round(E_D_R, 5) == np.round(E_D_L, 5)
                       == np.round(E_U_R, 5)
                       == np.round(E_U_L, 5)):
    print("Expectation value is the same in all directions")
print(E_D_R, E_D_L, E_U_R, E_U_L)

Expectation value is the same in all directions
10.525147639449782 10.525147639449775 10.525147639449782 10.525147639449775


In [106]:
MPS = left_canonical(MPS, N)

Singular Value: [1.]


In [107]:
### MANUAL CHECK CANONICAL FORM ####
# Information in DMRG Schollwöck 4.4 and Delft MPS lecture
# Goal: Contract left dimension and physical dimension to get identity at all sites

# First site has left dimension 1, so we contract physical dimension
test_identity = np.einsum('ij, ib->jb', MPS[0], MPS[0])
print("Pos", "1", ":\n", test_identity)
for i in range(1, len(MPS)-1):
    # We contract left dimension and physical dimension for each site
    test_identity = np.einsum('ijk, ijc->kc', MPS[i], MPS[i])
    print("Pos", i+1, ":\n", test_identity)
# Last site has right dimension 1, so result is a singular number
test_identity = np.einsum('ij, ij', MPS[-1], MPS[-1])
print("Pos", N, ":\n", test_identity)

Pos 1 :
 [[ 1.00000000e+00 -5.55111512e-17]
 [-5.55111512e-17  1.00000000e+00]]
Pos 2 :
 [[1.00000000e+00 2.75929453e-17]
 [2.75929453e-17 1.00000000e+00]]
Pos 3 :
 [[ 1.00000000e+00 -3.77302356e-17]
 [-3.77302356e-17  1.00000000e+00]]
Pos 4 :
 [[1. 0.]
 [0. 1.]]
Pos 5 :
 [[ 1.00000000e+00 -1.11889664e-16]
 [-1.11889664e-16  1.00000000e+00]]
Pos 6 :
 [[1.00000000e+00 5.55111512e-17]
 [5.55111512e-17 1.00000000e+00]]
Pos 7 :
 [[1.00000000e+00 5.55111512e-17]
 [5.55111512e-17 1.00000000e+00]]
Pos 8 :
 [[1.00000000e+00 5.55111512e-17]
 [5.55111512e-17 1.00000000e+00]]
Pos 9 :
 [[1.00000000e+00 7.32920669e-17]
 [7.32920669e-17 1.00000000e+00]]
Pos 10 :
 [[ 1.00000000e+00 -1.60028241e-16]
 [-1.60028241e-16  1.00000000e+00]]
Pos 11 :
 [[1.00000000e+00 5.55111512e-17]
 [5.55111512e-17 1.00000000e+00]]
Pos 12 :
 [[1. 0.]
 [0. 1.]]
Pos 13 :
 [[ 1.00000000e+00 -1.52221985e-16]
 [-1.52221985e-16  1.00000000e+00]]
Pos 14 :
 [[1. 0.]
 [0. 1.]]
Pos 15 :
 1.0


In [91]:
### MANUAL CHECK NORM ON BOND DIMENSION ####
test_identity = np.einsum('ij, aj->ia', MPS[0], MPS[0])
norm = test_identity
for i in range(1, len(MPS)-1):
    test_identity = np.einsum('ijk, ijc->kc', MPS[i], MPS[i])
    norm = norm @ test_identity
test_identity = np.einsum('ij, ij', MPS[-1], MPS[-1])
norm = norm * test_identity
norm = np.einsum('ij, ij', norm, norm)
print(norm)

[[1.00000000e+00 1.66533454e-16]
 [1.66533454e-16 1.00000000e+00]]
2.0000000000000018


In [89]:
### MANUAL CHECK NORM ON BOND DIMENSION ####
test_identity = np.einsum('ij, ib->jb', MPS[0], MPS[0])
norm = test_identity
for i in range(1, len(MPS)-1):
    test_identity = np.einsum('ijk, ijc->kc', MPS[i], MPS[i])
    norm = norm @ test_identity
test_identity = np.einsum('ij, ij', MPS[-1], MPS[-1])
norm = norm * test_identity
norm = np.einsum('ij, ij', norm, norm)
print(norm)

2.000000000000002


In [77]:
#### CHECK TENSOR SHAPES ####
for tensor in MPS:
    print(tensor.shape)

(2, 2)
(2, 2, 2)
(2, 2, 2)
(2, 2, 2)
(2, 2, 2)
(2, 2, 2)
(2, 2, 2)
(2, 2, 2)
(2, 2, 2)
(2, 2, 2)
(2, 2, 2)
(2, 2, 2)
(2, 2, 2)
(2, 2, 2)
(2, 2)


In [53]:
######################## EXPECTATION VALUE #############################################
E_D_R = calculateExpectation(MPS, MPO, MPS, 'down', 'right')
E_D_L = calculateExpectation(MPS, MPO, MPS, 'down', 'left')
E_U_R = calculateExpectation(MPS, MPO, MPS, 'up', 'right')
E_U_L = calculateExpectation(MPS, MPO, MPS, 'up', 'left')

# Rounding necessary since sometimes the values are slightly off
# Most likely due to rounding errors in computation
if (np.round(E_D_R, 5) == np.round(E_D_L, 5)
                       == np.round(E_U_R, 5)
                       == np.round(E_U_L, 5)):
    print("Expectation value is the same in all directions")
print(E_D_R, E_D_L, E_U_R, E_U_L)

Expectation value is the same in all directions
3.032833950867801 3.032833950867803 3.032833950867801 3.032833950867803


In [13]:
# ##### MANUAL NORM ########
# temp0 = np.einsum('ij, ib->jb', updated_MPS[0], updated_MPS[0])
# temp0 = np.reshape(temp0, (updated_MPS[0].shape[1]**2))
# temp1 = np.einsum('ijk, abk->iajb', updated_MPS[1], updated_MPS[1])
# temp1 = np.reshape(temp1, (updated_MPS[1].shape[0]**2, updated_MPS[1].shape[1]**2))
# norm = np.einsum('i, ik->k', temp0, temp1)

# for i in range(2, len(updated_MPS)-1):
#     temp = np.einsum('ijk, abk->iajb', updated_MPS[i], updated_MPS[i])
#     temp = np.reshape(temp, (updated_MPS[i].shape[0]**2, updated_MPS[i].shape[1]**2))
#     norm = np.einsum('i, ik->k', norm, temp)

# temp2 = np.einsum('ij, ib->jb', updated_MPS[-1], updated_MPS[-1])
# temp2 = np.reshape(temp2, (updated_MPS[-1].shape[1]**2))

# #norm = np.einsum('i, ik->k', temp0, temp1)
# norm = np.einsum('i, i', norm, temp2)
# print(norm)

In [138]:
# # ############## MANUAL TESTS FOR N = 3 #################################
# # ####### CONTRACT HAMILTONIAN LEFT AND RIGHT ########
# temp = contract_horizontal(MPO[0], MPO[1], 'right')
# H_right = contract_horizontal(temp, MPO[2], 'right')
# temp = contract_horizontal(MPO[2], MPO[1], 'left')
# H_left = contract_horizontal(temp, MPO[0], 'left')
# if (H_right.all() == H_left.all()):
#     print("Hamiltonian contracts correctly")

# # ######## EXPECTATION VALUE DOWN, RIGHT ##########
# # Left lattice bra->H->ket
# temp = contract_vertical(MPS[0], MPO[0], 'down')
# left = contract_vertical(temp, MPS[0], 'down')

# # Inner lattice bra->H->ket
# temp = contract_vertical(MPS[1], MPO[1], 'down')
# inner = contract_vertical(temp, MPS[1], 'down')

# # Right lattice bra->H->ket
# temp = contract_vertical(MPS[2], MPO[2], 'down')
# right = contract_vertical(temp, MPS[2], 'down')

# temp = contract_horizontal(left, inner, 'right')
# E_down_right = contract_horizontal(temp, right, 'right')

# ###### EXPECTATION VALUE UP, RIGHT ###########
# # Left lattice ket->H->bra
# temp = contract_vertical(MPS[0], MPO[0], 'up')
# left = contract_vertical(temp, MPS[0], 'up')

# # Inner lattice ket->H->bra
# temp = contract_vertical(MPS[1], MPO[1], 'up')
# inner = contract_vertical(temp, MPS[1], 'up')

# # Right lattice ket->H->bra
# temp = contract_vertical(MPS[2], MPO[2], 'up')
# right = contract_vertical(temp, MPS[2], 'up')

# temp = contract_horizontal(left, inner, 'right')
# E_up_right = contract_horizontal(temp, right, 'right')

# ###### EXPECTATION VALUE UP, LEFT ###########
# # Right lattice bra->H->ket
# temp = contract_vertical(MPS[2], MPO[2], 'up')
# right = contract_vertical(temp, MPS[2], 'up')

# # Inner lattice bra->H->ket
# temp = contract_vertical(MPS[1], MPO[1], 'up')
# inner = contract_vertical(temp, MPS[1], 'up')

# # Left lattice bra->H->ket
# temp = contract_vertical(MPS[0], MPO[0], 'up')
# left = contract_vertical(temp, MPS[0], 'up')

# temp = contract_horizontal(right, inner, 'left')
# E_up_left = contract_horizontal(temp, left, 'left')

# ###### EXPECTATION VALUE DOWN, LEFT ###########
# # Right lattice bra->H->ket
# temp = contract_vertical(MPS[2], MPO[2], 'down')
# right = contract_vertical(temp, MPS[2], 'down')

# # Inner lattice bra->H->ket
# temp = contract_vertical(MPS[1], MPO[1], 'down')
# inner = contract_vertical(temp, MPS[1], 'down')

# # Left lattice bra->H->ket
# temp = contract_vertical(MPS[0], MPO[0], 'down')
# left = contract_vertical(temp, MPS[0], 'down')

# temp = contract_horizontal(right, inner, 'left')
# E_down_left = contract_horizontal(temp, left, 'left')

# ######## EXPECTATION VALUE ZIG-ZAG ##########
# # Left lattice bra->H->ket
# temp = contract_vertical(MPS[0], MPO[0], 'down')
# left = contract_vertical(temp, MPS[0], 'down')

# # Inner lattice ket->H->bra
# temp = contract_vertical(MPS[1], MPO[1], 'up')
# inner = contract_vertical(temp, MPS[1], 'up')

# # Right lattice bra->H->ket
# temp = contract_vertical(MPS[2], MPO[2], 'down')
# right = contract_vertical(temp, MPS[2], 'down')

# temp = contract_horizontal(left, inner, 'right')
# E_zig_zag = contract_horizontal(temp, right, 'right')

# if (E_down_right.all() == E_down_left.all() == E_up_right.all() == E_up_left.all() == E_zig_zag.all()):
#      print("Expectation value contracts in all directions correctly")

# ######################## EXPECTATION VALUE #############################################
# E_D_R = calculateExpectation(MPS, MPO, MPS, 'down', 'right')
# E_D_L = calculateExpectation(MPS, MPO, MPS, 'down', 'left')
# E_U_R = calculateExpectation(MPS, MPO, MPS, 'up', 'right')
# E_U_L = calculateExpectation(MPS, MPO, MPS, 'up', 'left')

# # Rounding necessary since sometimes the values are slightly off
# # Most likely due to rounding errors in computation
# if (np.round(E_D_R, 5) == np.round(E_D_L, 5)
#                        == np.round(E_U_R, 5)
#                        == np.round(E_U_L, 5)):
#     print("Expectation value is the same in all directions")
# print(E_D_R, E_D_L, E_U_R, E_U_L)